spring.application.name=71-real-estate-backend
server.port=9193
spring.datasource.url=jdbc\:h2\:mem\:realestatedb
spring.datasource.username=sa
spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true\n
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
